from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE accounts_user
            ADD COLUMN IF NOT EXISTS is_verified boolean NOT NULL DEFAULT false;

            CREATE TABLE IF NOT EXISTS accounts_emailverificationotp (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                otp_hash varchar(128) NOT NULL,
                expires_at timestamp with time zone NOT NULL,
                attempts smallint NOT NULL DEFAULT 0 CHECK (attempts >= 0),
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                user_id bigint NOT NULL UNIQUE
                    REFERENCES accounts_user(id)
                    DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS accounts_emailverificationotp;

            ALTER TABLE accounts_user
            DROP COLUMN IF EXISTS is_verified;
            """,
        ),
    ]
