"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
def _read_bool(name: str, default: bool = False) -> bool:
    """
    Read a boolean-like environment value safely.

    python-decouple's bool casting raises on values like "release",
    so we normalize a few common deployment strings here instead of
    crashing during settings import.
    """

    raw_value = config(name, default=default)

    if isinstance(raw_value, bool):
        return raw_value

    value = str(raw_value).strip().lower()

    if value in {"1", "true", "t", "yes", "y", "on"}:
        return True

    if value in {"0", "false", "f", "no", "n", "off", "release", "prod", "production"}:
        return False

    return default


def _read_text(name: str, default: str = "") -> str:
    """
    Read a text environment value safely.

    Blank values fall back to the provided default so a set-but-empty
    env var does not disable a required URL configuration.
    """

    raw_value = config(name, default=default)

    if raw_value is None:
        return default

    value = str(raw_value).strip()
    return value or default


DEBUG = _read_bool("DEBUG", default=False)

ALLOWED_HOSTS = [
    host.strip()
    for host in config(
        "ALLOWED_HOSTS",
        default="localhost,127.0.0.1,[::1],testserver",
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party Apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    # Local Apps
    'accounts.apps.AccountsConfig',
    'dashboard.apps.DashboardConfig',
    'projects.apps.ProjectsConfig',
    'tasks.apps.TasksConfig',
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Allow React Frontend
CORS_ALLOW_ALL_ORIGINS = True

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "login": "10/minute",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=24),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

EMAIL_VERIFICATION_OTP_EXPIRY_MINUTES = config(
    "EMAIL_VERIFICATION_OTP_EXPIRY_MINUTES",
    default=10,
    cast=int,
)
DEFAULT_FROM_EMAIL = _read_text(
    "DEFAULT_FROM_EMAIL",
    default="no-reply@jiralite.local",
)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=None, cast=int)
RESEND_VERIFICATION_COOLDOWN_SECONDS = config(
    "RESEND_VERIFICATION_COOLDOWN_SECONDS",
    default=60,
    cast=int,
)
RESEND_VERIFICATION_EMAIL_LIMIT_PER_HOUR = config(
    "RESEND_VERIFICATION_EMAIL_LIMIT_PER_HOUR",
    default=5,
    cast=int,
)
RESEND_VERIFICATION_IP_LIMIT_PER_HOUR = config(
    "RESEND_VERIFICATION_IP_LIMIT_PER_HOUR",
    default=20,
    cast=int,
)
SIGNUP_EMAIL_LIMIT_PER_HOUR = config(
    "SIGNUP_EMAIL_LIMIT_PER_HOUR",
    default=10,
    cast=int,
)
SIGNUP_IP_LIMIT_PER_HOUR = config(
    "SIGNUP_IP_LIMIT_PER_HOUR",
    default=25,
    cast=int,
)
LOGIN_EMAIL_LIMIT_PER_MINUTE = config(
    "LOGIN_EMAIL_LIMIT_PER_MINUTE",
    default=10,
    cast=int,
)
LOGIN_IP_LIMIT_PER_MINUTE = config(
    "LOGIN_IP_LIMIT_PER_MINUTE",
    default=20,
    cast=int,
)
PROJECT_INVITATION_EXPIRY_HOURS = config(
    "PROJECT_INVITATION_EXPIRY_HOURS",
    default=48,
    cast=int,
)
BACKEND_BASE_URL = config(
    "BACKEND_BASE_URL",
    default="http://127.0.0.1:8000",
)
FRONTEND_URL = _read_text(
    "FRONTEND_URL",
    default="http://127.0.0.1:5173",
)
FRONTEND_ACCEPT_INVITATION_URL = _read_text(
    "FRONTEND_ACCEPT_INVITATION_URL",
    default="http://127.0.0.1:5173/invitations/respond",
)
