import {
  useMemo,
  useState,
} from "react";

import { toast } from "react-toastify";

import {
  updateTaskStatus,
} from "../../services/projectService";

const TaskStatusControl = ({
  task,
  canUpdateStatus = true,
  onTaskUpdated,
}) => {
  const [
    isUpdating,
    setIsUpdating,
  ] = useState(false);

  // ==========================================
  // CURRENT STATUS
  // ==========================================

  const currentStatus =
    task?.status || "TODO";

  // ==========================================
  // NEXT VALID STATUS
  // ==========================================
  //
  // Backend workflow:
  //
  // TODO
  //   ↓
  // IN_PROGRESS
  //   ↓
  // DONE
  //
  // IMPORTANT:
  //
  // TODO -> DONE
  //
  // is invalid according to backend.
  // ==========================================

  const nextStatus =
    useMemo(() => {
      switch (currentStatus) {
        case "TODO":
          return {
            value:
              "IN_PROGRESS",

            buttonLabel:
              "Start task",

            description:
              "Move this task from To Do to In Progress.",
          };

        case "IN_PROGRESS":
          return {
            value: "DONE",

            buttonLabel:
              "Mark as done",

            description:
              "Complete this task and mark it as Done.",
          };

        case "DONE":
          return null;

        default:
          return null;
      }
    }, [currentStatus]);

  // ==========================================
  // UPDATE STATUS
  //
  // PATCH /api/tasks/{taskId}/status/
  // ==========================================

  const handleStatusUpdate =
    async () => {
      if (!task?.id) {
        toast.error(
          "Task ID is missing.",
        );

        return;
      }

      if (!canUpdateStatus) {
        toast.error(
          "You are not allowed to update this task status.",
        );

        return;
      }

      if (!nextStatus?.value) {
        return;
      }

      try {
        setIsUpdating(true);

        /*
          Only the NEXT valid status
          is sent.

          TODO
            → IN_PROGRESS

          IN_PROGRESS
            → DONE

          Direct TODO → DONE is never
          generated by this component.
        */

        const response =
          await updateTaskStatus(
            task.id,
            nextStatus.value,
          );

        const updatedTask =
          response?.data;

        if (!updatedTask?.id) {
          throw new Error(
            "Task status was updated but updated task data was not returned.",
          );
        }

        /*
          Backend returns the complete
          updated task.

          Send it back to parent so
          TaskDetails.jsx can do:

          setTask(updatedTask)

          This updates the UI instantly
          without page refresh.
        */

        onTaskUpdated?.(
          updatedTask,
        );

        toast.success(
          response?.message ||
            "Task status updated successfully.",
        );
      } catch (error) {
        console.error(
          "Update task status failed:",
          error,
        );

        toast.error(
          error?.message ||
            "Unable to update task status.",
        );
      } finally {
        setIsUpdating(false);
      }
    };

  if (!task) {
    return null;
  }

  return (
    <section
      className="
        rounded-[20px]
        border
        border-slate-200
        bg-white
        p-6
        shadow-[0_5px_18px_rgba(15,30,51,0.05)]
      "
    >
      {/* =====================================
          HEADER
      ====================================== */}

      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start">
        <div>
          <h2 className="text-lg font-black text-[#14223A]">
            Task status
          </h2>

          <p className="mt-1 text-sm leading-6 text-slate-500">
            Track this task through its
            workflow.
          </p>
        </div>

        <StatusBadge
          status={
            currentStatus
          }
        />
      </div>

      {/* =====================================
          WORKFLOW
      ====================================== */}

      <div className="mt-6">
        <div className="grid grid-cols-3 gap-2 sm:gap-3">
          {/* TODO */}

          <WorkflowStep
            label="To Do"
            number="1"
            active={
              currentStatus ===
              "TODO"
            }
            completed={
              currentStatus ===
                "IN_PROGRESS" ||
              currentStatus ===
                "DONE"
            }
          />

          {/* IN PROGRESS */}

          <WorkflowStep
            label="In Progress"
            number="2"
            active={
              currentStatus ===
              "IN_PROGRESS"
            }
            completed={
              currentStatus ===
              "DONE"
            }
          />

          {/* DONE */}

          <WorkflowStep
            label="Done"
            number="3"
            active={
              currentStatus ===
              "DONE"
            }
            completed={false}
          />
        </div>

        {/* ===================================
            WORKFLOW CONNECTOR TEXT
        ==================================== */}

        <div className="mt-3 flex items-center justify-center gap-2 text-xs font-semibold text-slate-400">
          <span>TODO</span>

          <span>→</span>

          <span>IN PROGRESS</span>

          <span>→</span>

          <span>DONE</span>
        </div>
      </div>

      {/* =====================================
          UPDATE CONTROL
      ====================================== */}

      <div className="mt-6 border-t border-slate-100 pt-5">
        {!canUpdateStatus ? (
          /*
            READ ONLY

            This state is available if
            parent explicitly disables
            status changes.
          */

          <div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">
            <p className="text-sm font-bold text-slate-600">
              Read-only task
            </p>

            <p className="mt-1 text-xs leading-5 text-slate-500">
              You do not have permission
              to update this task status.
            </p>
          </div>
        ) : currentStatus ===
          "DONE" ? (
          /*
            COMPLETED TASK
          */

          <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-4">
            <div className="flex items-start gap-3">
              <div
                className="
                  flex
                  h-9
                  w-9
                  shrink-0
                  items-center
                  justify-center
                  rounded-full
                  bg-emerald-100
                  text-lg
                  font-black
                  text-emerald-700
                "
              >
                ✓
              </div>

              <div>
                <p className="text-sm font-extrabold text-emerald-700">
                  Task completed
                </p>

                <p className="mt-1 text-xs leading-5 text-emerald-600">
                  This task has reached
                  the final workflow
                  status.
                </p>

                {task?.completed_at && (
                  <p className="mt-2 text-xs font-bold text-emerald-700">
                    Completed{" "}
                    {formatDateTime(
                      task.completed_at,
                    )}
                  </p>
                )}
              </div>
            </div>
          </div>
        ) : (
          /*
            NEXT STATUS ACTION
          */

          <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
            <div>
              <p className="text-sm font-extrabold text-[#14223A]">
                {nextStatus
                  ?.buttonLabel}
              </p>

              <p className="mt-1 text-xs leading-5 text-slate-500">
                {
                  nextStatus
                    ?.description
                }
              </p>
            </div>

            <button
              type="button"
              onClick={
                handleStatusUpdate
              }
              disabled={
                isUpdating
              }
              className="
                inline-flex
                shrink-0
                items-center
                justify-center
                gap-2
                rounded-xl
                bg-[#3563E9]
                px-5
                py-3
                text-sm
                font-extrabold
                text-white
                shadow-[0_8px_20px_rgba(53,99,233,0.22)]
                transition
                hover:bg-[#2F58D3]
                disabled:cursor-not-allowed
                disabled:opacity-60
              "
            >
              {isUpdating ? (
                <>
                  <LoadingSpinner />

                  Updating...
                </>
              ) : (
                <>
                  {currentStatus ===
                  "TODO" ? (
                    <StartIcon />
                  ) : (
                    <DoneIcon />
                  )}

                  {
                    nextStatus
                      ?.buttonLabel
                  }
                </>
              )}
            </button>
          </div>
        )}
      </div>

      {/* =====================================
          PERMISSION INFORMATION
      ====================================== */}

      {canUpdateStatus &&
        currentStatus !==
          "DONE" && (
          <div className="mt-4 rounded-xl bg-slate-50 px-4 py-3">
            <p className="text-xs leading-5 text-slate-500">
              Status updates follow the
              workflow in order. A task
              must be started before it
              can be marked as completed.
            </p>
          </div>
        )}
    </section>
  );
};

// ==========================================
// WORKFLOW STEP
// ==========================================

const WorkflowStep = ({
  label,
  number,
  active,
  completed,
}) => {
  return (
    <div
      className={`
        relative
        rounded-xl
        border
        px-2
        py-4
        text-center
        transition
        sm:px-4
        ${
          active
            ? "border-[#3563E9] bg-blue-50"
            : completed
              ? "border-emerald-200 bg-emerald-50"
              : "border-slate-200 bg-slate-50"
        }
      `}
    >
      <div
        className={`
          mx-auto
          flex
          h-7
          w-7
          items-center
          justify-center
          rounded-full
          text-xs
          font-black
          ${
            active
              ? "bg-[#3563E9] text-white"
              : completed
                ? "bg-emerald-500 text-white"
                : "bg-slate-200 text-slate-500"
          }
        `}
      >
        {completed
          ? "✓"
          : number}
      </div>

      <p
        className={`
          mt-2
          text-[11px]
          font-extrabold
          sm:text-xs
          ${
            active
              ? "text-[#3563E9]"
              : completed
                ? "text-emerald-700"
                : "text-slate-500"
          }
        `}
      >
        {label}
      </p>
    </div>
  );
};

// ==========================================
// STATUS BADGE
// ==========================================

const StatusBadge = ({
  status,
}) => {
  const styles = {
    TODO:
      "border-slate-200 bg-slate-100 text-slate-600",

    IN_PROGRESS:
      "border-blue-200 bg-blue-50 text-blue-700",

    DONE:
      "border-emerald-200 bg-emerald-50 text-emerald-700",
  };

  return (
    <span
      className={`
        inline-flex
        w-fit
        rounded-full
        border
        px-3
        py-1.5
        text-xs
        font-extrabold
        ${
          styles[status] ||
          styles.TODO
        }
      `}
    >
      {formatStatus(status)}
    </span>
  );
};

// ==========================================
// START ICON
// ==========================================

const StartIcon = () => {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      className="h-4 w-4"
    >
      <path d="m8 5 11 7-11 7Z" />
    </svg>
  );
};

// ==========================================
// DONE ICON
// ==========================================

const DoneIcon = () => {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      className="h-4 w-4"
    >
      <circle
        cx="12"
        cy="12"
        r="9"
      />

      <path d="m8 12 2.5 2.5L16 9" />
    </svg>
  );
};

// ==========================================
// LOADING SPINNER
// ==========================================

const LoadingSpinner = () => {
  return (
    <span
      className="
        h-4
        w-4
        animate-spin
        rounded-full
        border-2
        border-white/40
        border-t-white
      "
    />
  );
};

// ==========================================
// FORMAT STATUS
// ==========================================

const formatStatus = (
  status,
) => {
  switch (status) {
    case "TODO":
      return "TO DO";

    case "IN_PROGRESS":
      return "IN PROGRESS";

    case "DONE":
      return "DONE";

    default:
      return (
        status || "TO DO"
      );
  }
};

// ==========================================
// FORMAT DATE TIME
// ==========================================

const formatDateTime = (
  value,
) => {
  if (!value) {
    return "";
  }

  const date =
    new Date(value);

  if (
    Number.isNaN(
      date.getTime(),
    )
  ) {
    return "";
  }

  return date.toLocaleString(
    "en-US",
    {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
    },
  );
};

export default TaskStatusControl;